version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u242-jdk

    working_directory: ~/work

    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "pom.xml" }}
      - run:
          name: Perform Build
          command: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: cache-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/circleci2-0.0.1-SNAPSHOT.jar
      - store_test_results:
          path: target/surefire-reports
      - persist_to_workspace:
          root: target
          paths:
            - circleci2-0.0.1-SNAPSHOT.jar

workflows:
  build-deploy:
    jobs:
      - build
