version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  store:
    docker:
    - image: circleci/openjdk:8-jdk-node
    parallelism: 1   
    steps:
      - store_artifacts:
          path: target/*.jar 

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - store
   
